# Generated by Django 6.0.6 on 2026-06-22 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(help_text='Từ vựng tiếng Anh', max_length=100)),
                ('pronunciation', models.CharField(blank=True, help_text='Phiên âm quốc tế IPA', max_length=100, null=True)),
                ('part_of_speech', models.CharField(help_text='Loại từ: Noun, Verb, Adj...', max_length=50)),
                ('vietnamese_meaning', models.CharField(help_text='Nghĩa tiếng Việt', max_length=255)),
                ('example_sentence', models.TextField(blank=True, help_text='Câu ví dụ', null=True)),
                ('example_meaning', models.TextField(blank=True, help_text='Nghĩa tiếng Việt của câu ví dụ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LEARNED', 'Đã thuộc'), ('REVIEW', 'Cần học lại')], default='REVIEW', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to='core.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
