# Generated by Django 6.0.6 on 2026-06-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên chủ đề', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Chủ đề của từ vựng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='core.topic'),
        ),
    ]
